// Generated by gencpp from file ysrobotodom/robotencoder.msg
// DO NOT EDIT!


#ifndef YSROBOTODOM_MESSAGE_ROBOTENCODER_H
#define YSROBOTODOM_MESSAGE_ROBOTENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ysrobotodom
{
template <class ContainerAllocator>
struct robotencoder_
{
  typedef robotencoder_<ContainerAllocator> Type;

  robotencoder_()
    : leftencoder(0)
    , rightencoder(0)
    , seq(0)  {
    }
  robotencoder_(const ContainerAllocator& _alloc)
    : leftencoder(0)
    , rightencoder(0)
    , seq(0)  {
  (void)_alloc;
    }



   typedef int32_t _leftencoder_type;
  _leftencoder_type leftencoder;

   typedef int32_t _rightencoder_type;
  _rightencoder_type rightencoder;

   typedef uint32_t _seq_type;
  _seq_type seq;





  typedef boost::shared_ptr< ::ysrobotodom::robotencoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ysrobotodom::robotencoder_<ContainerAllocator> const> ConstPtr;

}; // struct robotencoder_

typedef ::ysrobotodom::robotencoder_<std::allocator<void> > robotencoder;

typedef boost::shared_ptr< ::ysrobotodom::robotencoder > robotencoderPtr;
typedef boost::shared_ptr< ::ysrobotodom::robotencoder const> robotencoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ysrobotodom::robotencoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ysrobotodom::robotencoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ysrobotodom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ysrobotodom': ['/home/ydd/ysodom/catkin_ws/src/ysrobotodom/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ysrobotodom::robotencoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ysrobotodom::robotencoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ysrobotodom::robotencoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ysrobotodom::robotencoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ysrobotodom::robotencoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ysrobotodom::robotencoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ysrobotodom::robotencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2622be2aa7904b3e81edff5d7971b517";
  }

  static const char* value(const ::ysrobotodom::robotencoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2622be2aa7904b3eULL;
  static const uint64_t static_value2 = 0x81edff5d7971b517ULL;
};

template<class ContainerAllocator>
struct DataType< ::ysrobotodom::robotencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ysrobotodom/robotencoder";
  }

  static const char* value(const ::ysrobotodom::robotencoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ysrobotodom::robotencoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 leftencoder\n\
int32 rightencoder\n\
uint32 seq\n\
";
  }

  static const char* value(const ::ysrobotodom::robotencoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ysrobotodom::robotencoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftencoder);
      stream.next(m.rightencoder);
      stream.next(m.seq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotencoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ysrobotodom::robotencoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ysrobotodom::robotencoder_<ContainerAllocator>& v)
  {
    s << indent << "leftencoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.leftencoder);
    s << indent << "rightencoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.rightencoder);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YSROBOTODOM_MESSAGE_ROBOTENCODER_H
